### ISSUE TITLE
selector fxHide.xs doesn't work

### ISSUE THREAD

**Issue by skined90** [angular/flex-layout#62]
fxHide.[any-size] doesn't work (It doesn't hide an element)

**Comment by ThomasBurleson** [comment]
@skined90 - please provide a CodePen or Plunkr to demonstrate the issue.

> Meanwhile I will research on our end ;-).

**Comment by skined90** [comment]
Here is the plunker [https://plnkr.co/edit/h4ZSa0YI9QruCD5MFNDo?p=preview](url)

The first div has a fxHide.xs but it doesn't hide when I resize screen to be smaller than 599px. You can try with any other suffix (sm, md, lg)

**Comment by ThomasBurleson** [comment]
So you encountered a KNOWN bug #59.

The fix is to add the default API also with the responsive one(s):

```
<div fxHide="false"  fxHide.xs fxFlex="20">  fxFlex="20"  </div>
```

**Comment by ThomasBurleson** [comment]
Refs #59

**Comment by ThomasBurleson** [comment]
Fixed in [Angular SHA](https://github.com/angular/angular/commit/881eb894bc17092e61842e8b37955344829510c9): will be available in Angular v4.0.0-beta.2.

**Comment by ThomasBurleson** [comment]
Also liable in Angular v2.4.1

**Comment by ThomasBurleson** [comment]
Reopening to add tests.

**Comment by netmikey** [comment]
I am using Angular 2.4.4 and flex-layout 2.0.0-beta.3 but it seems like this still isn't working.

I guess having to always use 2 attributes to simply hide an element for a given breakpoint isn't intended?

    <span fxHide="false" fxHide.xs>Hide this on Phone only</span>

In this example, the need for `fxHide="false"` is unexpected. 

Also, binding like the following still yields the known angular error (though it should have been fixed in Angular 2.4.2 according to the [release notes](https://github.com/angular/angular/blob/master/CHANGELOG.md#242-2017-01-06)?):

    <span [fxHide.xs]="dynamicProperty">Maybe hide this on phone</span>

**Comment by ThomasBurleson** [comment]
@netmikey, @skined90 - Thx for the alert. You helped us discover another very subtle, *hidden* bug where the `,` was missing in many of the directive selector lists.   

> See Pull Request #121 for fixes.
