### ISSUE TITLE
Orientation breakpoints support

### ISSUE THREAD

**Issue by laulaaa** [angular/flex-layout#745]
Hello. 

I don't know if the orientation breakpoints are not working in the latest version, or I don't know how to use it.  I have read the documentation provided  ([link](https://github.com/angular/flex-layout/wiki/Breakpoints#adding-the-orientation-breakpoints)), but I'm still not sure. 

As you said in the documentation, I add to the module the configuration:

```
import {FlexLayoutModule , ADD_ORIENTATION_BREAKPOINTS} from '@angular/flex-layout';

@NgModule({
  ...
  providers:    [ {provide: ADD_ORIENTATION_BREAKPOINTS, useValue: true} ]
})
```

Then I tried to use it in the component in this way:

  
```
         <div fxHide.web>
             <h1>Hide Web</h1>      
         </div>

         <div fxHide fxShow.web.portrait>
            <h1>Portrait Web</h1>      
          </div>

         <div fxHide fxShow.web.landscape>
             <h1>Landscape Web </h1>      
         </div>
```
#### What are the steps to reproduce?

Here are examples of my code: 

[Test 1 ](https://stackblitz.com/edit/orientation-laulaaa)
@angular: 5.2.4
@angular/flex-layout: 5.0.0-beta.14

[Test 2 ](https://stackblitz.com/edit/orientation-laulaaa-2)
@angular: 6.0.0
@angular/flex-layout: 6.0.0-beta.15

#### What is the expected behavior?

Can you provide a complete example of this feature? 
Which versions support this feature?
Am I forgetting something important?

**Comment by CaerusKaru** [comment]
Ok, I understand the confusion here, and it unfortunately doesn't come with an easy explanation.

The reason this is failing is because while those breakpoints are _registered_ with Flex Layout, the aliases are not _attached_ to each directive. Why? Because Angular at the moment requires explicitly enumerating all inputs on directives. You can _extend_ the directives and add the inputs, as explained in the doc, but it won't work out of the box.

The solution to this is explained in #17, which as you can tell by the date, was a limitation on this library from the start. This will (hopefully) be resolved by the time Angular hits v6.2, or before that if we can sufficiently prototype a new design.

The short of it is, this won't work out of the box, and we're working on making the user experience for this better.

**Comment by kalitine** [comment]
I tried recently with the latest angular version 8.1.1, but it didn't work. As @laulaaa I'm not sure whether its is fixed and I used it in a wrong way or it is not fixed yet. Anyway it would be nice to mention it in the [BreakPoints Wiki](https://github.com/angular/flex-layout/wiki/BreakPoints). Because after the wiki page it looks like it should work.
